# Generated by Django 5.2.1 on 2025-05-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiasUteis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('ignorar_domingos', models.BooleanField(default=True)),
                ('incluir_feriados', models.BooleanField(default=False)),
                ('feriados', models.TextField(blank=True, help_text='Insira as datas dos feriados separadas por vírgula (ex: 01/05/2025, 20/06/2025)')),
                ('total_dias_uteis', models.IntegerField(default=0)),
                ('dias_uteis_passados', models.IntegerField(default=0)),
                ('dias_uteis_restantes', models.IntegerField(default=0)),
            ],
        ),
    ]
