# Generated by Django 5.2.1 on 2025-06-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diasuteis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diasuteis',
            name='dias_uteis_lista',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
